sudo: required
dist: trusty
language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - compiler: clang
      env: TRAVIS_BRANCH=coverity_scan

env:
  global:
    secure: XwDsJGhc2p96UUnfail8Vlhplq1yoM8KWnpKcG6Imt7S7e5Z+qsspPGDXBXEgWXGrWxaQXNtZRG/GfwFJ5X7V3sPJqapIepnlFdlKlOXsdOnKbJATdezeERvkUEku+iqUShWnFyoq8M8+yjyVljq5/rZnY8nN/V0MZSpXzkqXS/V67wWthjRjp4KGnbf+wDOfXhhAvHkB6QWF5QnzYLUddVhw2IZaH+CbXKYEIL3nySAMytYKiJhx6m8G4aBpWDOXtoL1K21USQOhJmI/cF9MWdiet/qpE+tpLdytw34vYQbJWEWED2Waxa2hwanCGNE4rB0x+yA3yoM+fr/g5cN1F5/PVuNszof5QBYv/WrrP1WHIT3nAVmmgQ+LbF/3Yd+eVuoLggSIsyn+jrCEVl7qf3mhZHJl4MzY9d/jYZ+6k6j41O7UlUKnTBc6HOAGKBs4xl96uwjyp0cCpqPYOHSXU0AmFoirHKH96GZqLvFOxsSLzQAcTPkRy0nyqfterhnpAhm0PO8BVCw2xjEKiZ3juS15nS5MR8hmKy6obbONnC59vpTI01y3bwiZ0Lzj6c4s0pspMlC7EQmsg2eNxkMfgmFaUVYt3UCQyZDrAGmmk/bXJmxXmPJVopme/bRGo8+7rubfsNy4KDbEAbUcr7YiskQ3Bs0wjuCfyBGqUVVmpk=

addons:
  coverity_scan:
    project:
      name: $TRAVIS_REPO_SLUG
    notification_email: petre.p.eftime@intel.com
    build_command_prepend: cmake -DBUILDJAVA=$BUILDJAVA .
    build_command: make
    branch_pattern: coverity_scan

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - if `java -version`; then export BUILDJAVA=ON; else BUILDJAVA=OFF; fi
  - export PROJECT_NAME=$TRAVIS_REPO_SLUG
  - cmake -DBUILDJAVA=$BUILDJAVA .

script:
  - make
